name: Verify PR Builds and Passes Tests

on:
  pull_request:
    branches:
      - develop

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Check Branch target is not 'stable'
        run: |
          if [ ${{ github.base_ref }} == "stable" ]; then
            echo "Merge requests to stable branch are not allowed. Any update to 'stable' branch is applied automatically after updating 'develop'"
            exit 1
          fi

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build
        run: cargo build --release

      - name: Test
        run: cargo test
